package com.zsc.demo;

import com.zsc.demo.TStu;
import com.zsc.demo.TStuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TStuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    int countByExample(TStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    int deleteByExample(TStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    int insert(TStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    int insertSelective(TStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    List<TStu> selectByExample(TStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") TStu record, @Param("example") TStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    int updateByExample(@Param("record") TStu record, @Param("example") TStuExample example);
}