package com.zsc.demo;

public class TStu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.id
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.name
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.sex
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.age
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public TStu(String id, String name, String sex, Integer age) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public TStu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.id
     *
     * @return the value of t_stu.id
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.id
     *
     * @param id the value for t_stu.id
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.name
     *
     * @return the value of t_stu.name
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.name
     *
     * @param name the value for t_stu.name
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.sex
     *
     * @return the value of t_stu.sex
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.sex
     *
     * @param sex the value for t_stu.sex
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.age
     *
     * @return the value of t_stu.age
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.age
     *
     * @param age the value for t_stu.age
     *
     * @mbggenerated Sun Aug 25 15:41:49 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}